package com.project.poverenik.wsdl.izvestaji;

import com.project.poverenik.model.izvestaj.ObjectFactory;
import com.project.poverenik.model.izvestaj.Tbody;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2021-02-03T12:31:03.509+01:00
 * Generated source version: 3.2.1
 */
@WebService(targetNamespace = "http://izvestaji", name = "IzvestajServicePortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface IzvestajServicePortType {

    @WebMethod(action = "http://izvestaji/ws/getPodaci")
    @WebResult(name = "response", targetNamespace = "http://izvestaji", partName = "response")
    Tbody getPodaci();

    @WebMethod(action = "http://izvestaji/ws/podnesiIzvestaj")
    @WebResult(name = "response", targetNamespace = "http://izvestaji", partName = "response")
    java.lang.String podnesiIzvestaj(
            @WebParam(partName = "izvestajRef", name = "izvestajRef")
                    java.lang.String izvestajRef
    );
}
