PREFIX xs:     <http://www.w3.org/2001/XMLSchema#>

SELECT * FROM <http://localhost:8080/fusekiP/Tim7Dataset/data/tim7/metadata/zalbe>
WHERE { 
	?zalba_cutanje <http://examples/predicate/podnosilac> %s . 
}