package com.project.organ_vlasti.wsdl.izvestaj;

import com.project.organ_vlasti.model.izvestaji.ObjectFactory;
import com.project.organ_vlasti.model.izvestaji.Tbody;
import com.project.organ_vlasti.model.util.parametars.ParametarMap;
import com.project.organ_vlasti.model.util.parametars.RefIdList;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2021-02-03T22:42:03.977+01:00
 * Generated source version: 3.2.1
 * 
 */
@WebService(targetNamespace = "http://izvestaji", name = "IzvestajServicePortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface IzvestajServicePortType {

    @WebMethod(action = "http://izvestaji/ws/getRefs")
    @WebResult(name = "refs", targetNamespace = "http://izvestaji", partName = "refs")
    public RefIdList getRefs(
        @WebParam(partName = "parametars", name = "parametars")
                ParametarMap parametars
    );

    @WebMethod(action = "http://izvestaji/ws/getIzvestajById")
    @WebResult(name = "izvestaj", targetNamespace = "http://izvestaji", partName = "izvestaj")
    public Tbody getIzvestajById(
        @WebParam(partName = "id", name = "id")
        String id
    );
}
