
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.project.organ_vlasti.wsdl.obavestenje;

import com.project.organ_vlasti.model.obavestenje.Tobavestenje;
import com.project.organ_vlasti.service.ObavestenjeService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2021-01-30T17:19:13.056+01:00
 * Generated source version: 3.2.1
 * 
 */

@WebService(
                      serviceName = "ObavestenjeService",
                      portName = "ObavestenjeServiceSoapBinding",
                      targetNamespace = "http://www.obavestenje",
                      wsdlLocation = "classpath:wsdl/Obavestenje.wsdl",
                      endpointInterface = "com.project.organ_vlasti.wsdl.obavestenje.ObavestenjeServicePortType")
@Service
public class ObavestenjeServiceSoapBindingImpl implements ObavestenjeServicePortType {

    @Autowired
    ObavestenjeService obavestenjeService;

    private static final Logger LOG = Logger.getLogger(ObavestenjeServiceSoapBindingImpl.class.getName());

    /* (non-Javadoc)
     * @see obavestenje.ObavestenjeServicePortType#getObavestenjeByBroj(java.lang.String id)*
     */
    public Tobavestenje getObavestenjeByBroj(String id) {
        LOG.info("Executing operation getObavestenjeByBroj");
        System.out.println(id);
        try {
            Tobavestenje _return = obavestenjeService.getOne(id).getObavestenjeBody();
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
