package com.project.organ_vlasti.wsdl.obavestenje;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2021-01-30T17:19:13.104+01:00
 * Generated source version: 3.2.1
 * 
 */
@WebServiceClient(name = "ObavestenjeService", 
                  wsdlLocation = "classpath:wsdl/Obavestenje.wsdl",
                  targetNamespace = "http://www.obavestenje") 
public class ObavestenjeService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.obavestenje", "ObavestenjeService");
    public final static QName ObavestenjeServiceSoapBinding = new QName("http://www.obavestenje", "ObavestenjeServiceSoapBinding");
    static {
        URL url = ObavestenjeService.class.getClassLoader().getResource("wsdl/Obavestenje.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(ObavestenjeService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "classpath:wsdl/Obavestenje.wsdl");
        }       
        WSDL_LOCATION = url;   
    }

    public ObavestenjeService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ObavestenjeService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ObavestenjeService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public ObavestenjeService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ObavestenjeService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ObavestenjeService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns ObavestenjeServicePortType
     */
    @WebEndpoint(name = "ObavestenjeServiceSoapBinding")
    public ObavestenjeServicePortType getObavestenjeServiceSoapBinding() {
        return super.getPort(ObavestenjeServiceSoapBinding, ObavestenjeServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ObavestenjeServicePortType
     */
    @WebEndpoint(name = "ObavestenjeServiceSoapBinding")
    public ObavestenjeServicePortType getObavestenjeServiceSoapBinding(WebServiceFeature... features) {
        return super.getPort(ObavestenjeServiceSoapBinding, ObavestenjeServicePortType.class, features);
    }

}
