package com.project.email.wsdl;

import com.project.email.model.ObjectFactory;
import com.project.email.model.Tbody;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2021-02-01T17:56:31.240+01:00
 * Generated source version: 3.2.1
 */
@WebService(targetNamespace = "http://email", name = "EmailServicePortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface EmailServicePortType {

    @WebMethod(action = "http://email/ws/sendPlain")
    @WebResult(name = "response", targetNamespace = "http://email", partName = "response")
    String sendPlain(
            @WebParam(partName = "email", name = "email")
                    Tbody email
    );

    @WebMethod(action = "http://email/ws/sendAttach")
    @WebResult(name = "response", targetNamespace = "http://email", partName = "response")
    String sendAttach(
            @WebParam(partName = "email", name = "email")
                    Tbody email
    );
}
