
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.project.email.wsdl;

import com.project.email.model.Tbody;
import com.project.email.service.EmailService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import javax.jws.WebService;
import java.util.logging.Logger;


/**
 * This class was generated by Apache CXF 3.2.1
 * 2021-02-01T17:56:31.131+01:00
 * Generated source version: 3.2.1
 */

@WebService(
        serviceName = "EmailService",
        portName = "EmailServiceSoapBinding",
        targetNamespace = "http://email",
        wsdlLocation = "classpath:wsdl/Email.wsdl",
        endpointInterface = "com.project.email.wsdl.EmailServicePortType")
@Service
public class EmailServiceSoapBindingImpl implements EmailServicePortType {

    @Autowired
    EmailService emailService;
    private static final Logger LOG = Logger.getLogger(EmailServiceSoapBindingImpl.class.getName());

    /* (non-Javadoc)
     * @see email.EmailServicePortType#sendPlain(email.Tbody email)*
     */
    public String sendPlain(Tbody email) {
        LOG.info("Executing operation sendPlain");
        try {
            emailService.sendPlainMail(email);
            return "OK";
        } catch (Exception ex) {
            return null;
        }
    }

    /* (non-Javadoc)
     * @see email.EmailServicePortType#sendAttach(email.Tbody email)*
     */
    public String sendAttach(Tbody email) {
        LOG.info("Executing operation sendAttach");
        try {
            emailService.sendAttachMail(email);
            return "OK";
        } catch (Exception ex) {
            return null;
        }
    }

}
