
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.project.organ_vlasti.wsdl.resenje_ref;

import com.project.organ_vlasti.model.resenje.database.ResenjeRef;
import com.project.organ_vlasti.model.resenje.database.ObjectFactory;
import com.project.organ_vlasti.service.ResenjeRefService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2021-02-01T11:11:18.738+01:00
 * Generated source version: 3.2.1
 * 
 */

@WebService(
                      serviceName = "ResenjeRefService",
                      portName = "ResenjeRefServiceSoapBinding",
                      targetNamespace = "http://resenje",
                      wsdlLocation = "classpath:wsdl/ResenjeRef.wsdl",
                      endpointInterface = "com.project.organ_vlasti.wsdl.resenje_ref.ResenjeRefServicePortType")
@Service
public class ResenjeRefServiceSoapBindingImpl implements ResenjeRefServicePortType {

    @Autowired
    ResenjeRefService resenjeRefService;
    private static final Logger LOG = Logger.getLogger(ResenjeRefServiceSoapBindingImpl.class.getName());

    /* (non-Javadoc)
     * @see resenje.ResenjeRefServicePortType#setResenjeRef(java.lang.String resenjeRef)*
     */
    public String setResenjeRef(String resenjeRef) {
        LOG.info("Executing operation setResenjeRef");
        System.out.println(resenjeRef);
        try {
            ObjectFactory of = new ObjectFactory();
            ResenjeRef resenjeRefObj = of.createResenjeRef();
            resenjeRefObj.setBody(of.creBody());
            resenjeRefObj.getBody().setValue(resenjeRef);
            resenjeRefObj.getBody().setProcitano("ne");

            resenjeRefService.create(resenjeRefObj);

            return "OK";
        } catch (Exception ex) {
            return "Error";
        }
    }

}
