package com.project.organ_vlasti.wsdl.file;

import com.project.organ_vlasti.model.util.file.ObjectFactory;
import com.project.organ_vlasti.model.util.file.Tpath;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2021-02-06T13:49:12.485+01:00
 * Generated source version: 3.2.1
 * 
 */
@WebService(targetNamespace = "http://file", name = "FileServicePortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface FileServicePortType {

    @WebMethod(action = "http://file/ws/sendRdfFile")
    @WebResult(name = "path", targetNamespace = "http://file", partName = "path")
    public Tpath sendRdfFile(
        @WebParam(partName = "id", name = "id")
        String id
    );

    @WebMethod(action = "http://file/ws/sendJsonFile")
    @WebResult(name = "path", targetNamespace = "http://file", partName = "path")
    public Tpath sendJsonFile(
        @WebParam(partName = "id", name = "id")
        String id
    );
}
