package com.project.poverenik.wsdl.zalba_odluka;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2021-01-28T22:45:30.907+01:00
 * Generated source version: 3.2.1
 */
@WebServiceClient(name = "ZalbaOdlukaService",
        wsdlLocation = "classpath:wsdl/ZalbaOdluka.wsdl",
        targetNamespace = "http://www.zalbanaodlukucir")
public class ZalbaOdlukaService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.zalbanaodlukucir", "ZalbaOdlukaService");
    public final static QName ZalbaOdlukaServiceSoapBinding = new QName("http://www.zalbanaodlukucir", "ZalbaOdlukaServiceSoapBinding");

    static {
        URL url = ZalbaOdlukaService.class.getClassLoader().getResource("wsdl/ZalbaOdluka.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(ZalbaOdlukaService.class.getName())
                    .log(java.util.logging.Level.INFO,
                            "Can not initialize the default wsdl from {0}", "classpath:wsdl/ZalbaOdluka.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ZalbaOdlukaService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ZalbaOdlukaService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZalbaOdlukaService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ZalbaOdlukaService(WebServiceFeature... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ZalbaOdlukaService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ZalbaOdlukaService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }


    /**
     * @return returns ZalbaOdlukaServicePortType
     */
    @WebEndpoint(name = "ZalbaOdlukaServiceSoapBinding")
    public ZalbaOdlukaServicePortType getZalbaOdlukaServiceSoapBinding() {
        return super.getPort(ZalbaOdlukaServiceSoapBinding, ZalbaOdlukaServicePortType.class);
    }

    /**
     * @param features A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns ZalbaOdlukaServicePortType
     */
    @WebEndpoint(name = "ZalbaOdlukaServiceSoapBinding")
    public ZalbaOdlukaServicePortType getZalbaOdlukaServiceSoapBinding(WebServiceFeature... features) {
        return super.getPort(ZalbaOdlukaServiceSoapBinding, ZalbaOdlukaServicePortType.class, features);
    }

}
