package com.project.poverenik.wsdl.zalba_odluka;

import com.project.poverenik.model.zalba_odluka.ObjectFactory;
import com.project.poverenik.model.zalba_odluka.Tzalba;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2021-01-28T22:45:30.904+01:00
 * Generated source version: 3.2.1
 * 
 */
@WebService(targetNamespace = "http://www.zalbanaodlukucir", name = "ZalbaOdlukaServicePortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface ZalbaOdlukaServicePortType {

    @WebMethod(action = "http://www.zalbanaodlukucir/ws/getZalbaOdlukaById")
    @WebResult(name = "zalba_odluka", targetNamespace = "http://www.zalbanaodlukucir", partName = "zalba_odluka")
    public Tzalba getZalbaOdlukaById(
        @WebParam(partName = "id", name = "id")
        String id
    );
}
