PREFIX xs:     <http://www.w3.org/2001/XMLSchema#>

SELECT * FROM <http://localhost:8080/fusekiOV/Tim7Dataset/data/tim7/metadata/obavestenja>
WHERE { 
	%s <http://examples/predicate/datum> ?datum . 
	%s <http://examples/predicate/organ_vlasti> ?organ_vlasti . 
	%s <http://examples/predicate/podnosilac> ?podnosilac . 
	%s <http://examples/predicate/zahtev> zahtev . 