PREFIX xs:     <http://www.w3.org/2001/XMLSchema#>

SELECT * FROM <http://localhost:8080/fusekiOV/Tim7Dataset/data/tim7/metadata/zahtevi>
WHERE { 
	?zahtev <http://examples/predicate/datum> ?datum . 
	?zahtev <http://examples/predicate/organ_vlasti> ?organ_vlasti . 
	?zahtev <http://examples/predicate/mesto> ?mesto . 
	?zahtev <http://examples/predicate/podnosilac> %s . 
	FILTER ( ?datum >= "%s"^^<http://www.w3.org/2001/XMLSchema#date> 
	&& ?datum <= "%s"^^<http://www.w3.org/2001/XMLSchema#date>
	&& regex(UCASE(str(?mesto)), UCASE(".*%s.*"))
	&& regex(UCASE(str(?organ_vlasti)), UCASE(".*%s.*"))
	)
}