package com.project.poverenik.wsdl.resenje;

import com.project.poverenik.model.resenje.ObjectFactory;
import com.project.poverenik.model.resenje.Tresenje;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2021-01-27T22:45:27.304+01:00
 * Generated source version: 3.2.1
 * 
 */
@WebService(targetNamespace = "http://resenje", name = "ResenjeServicePortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface ResenjeServicePortType {

    @WebMethod(action = "http://resenje/ws/getResenjeByBroj")
    @WebResult(name = "resenje", targetNamespace = "http://resenje", partName = "resenje")
    public Tresenje getResenjeByBroj(
        @WebParam(partName = "broj", name = "broj")
        String broj
    );
}
