<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
				  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
				  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
				  targetNamespace="http://resenje"
				  xmlns:tns="http://resenje"
				  name="ResenjeService">
	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://resenje" schemaLocation="../xsd/resenje.xsd"/>
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="getResenjeRequest">
		<wsdl:part name="broj" type="xsd:string" />
	</wsdl:message>
	<wsdl:message name="getResenjeResponse">
		<wsdl:part name="result" type="tns:Tresenje" />
	</wsdl:message>

	<wsdl:portType name="ResenjeServicePortType">
		<wsdl:operation name="getResenjeByBroj">
			<wsdl:input message="tns:getResenjeRequest" />
			<wsdl:output message="tns:getResenjeResponse" />
		</wsdl:operation>
	</wsdl:portType>

	<wsdl:binding name="ResenjeServiceSoapBinding" type="tns:ResenjeServicePortType">
		<soap:binding style="rpc"  transport="http://schemas.xmlsoap.org/soap/http" />
		<wsdl:operation name="getResenjeByBroj">
			<soap:operation soapAction="http://resenje/ws/getResenjeByBroj" />
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="ResenjeService">
		<wsdl:port name="ResenjeServiceSoapBinding" binding="tns:ResenjeServiceSoapBinding">
			<soap:address location="http://localhost:8085/resenjePort" />
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>