package com.project.poverenik.wsdl.zalba_cutanje;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2021-01-28T01:12:23.526+01:00
 * Generated source version: 3.2.1
 */
@WebServiceClient(name = "ZalbaCutanjeService",
        wsdlLocation = "classpath:wsdl/ZalbaCutanje.wsdl",
        targetNamespace = "http://www.zalbacutanje")
public class ZalbaCutanjeService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.zalbacutanje", "ZalbaCutanjeService");
    public final static QName ZalbaCutanjeServiceSoapBinding = new QName("http://www.zalbacutanje", "ZalbaCutanjeServiceSoapBinding");

    static {
        URL url = ZalbaCutanjeService.class.getClassLoader().getResource("wsdl/ZalbaCutanje.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(ZalbaCutanjeService.class.getName())
                    .log(java.util.logging.Level.INFO,
                            "Can not initialize the default wsdl from {0}", "classpath:wsdl/ZalbaCutanje.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ZalbaCutanjeService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ZalbaCutanjeService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZalbaCutanjeService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ZalbaCutanjeService(WebServiceFeature... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ZalbaCutanjeService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ZalbaCutanjeService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }


    /**
     * @return returns ZalbaCutanjeServicePortType
     */
    @WebEndpoint(name = "ZalbaCutanjeServiceSoapBinding")
    public ZalbaCutanjeServicePortType getZalbaCutanjeServiceSoapBinding() {
        return super.getPort(ZalbaCutanjeServiceSoapBinding, ZalbaCutanjeServicePortType.class);
    }

    /**
     * @param features A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns ZalbaCutanjeServicePortType
     */
    @WebEndpoint(name = "ZalbaCutanjeServiceSoapBinding")
    public ZalbaCutanjeServicePortType getZalbaCutanjeServiceSoapBinding(WebServiceFeature... features) {
        return super.getPort(ZalbaCutanjeServiceSoapBinding, ZalbaCutanjeServicePortType.class, features);
    }

}
