package com.project.organ_vlasti.wsdl.izjasnjavanje;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2021-01-31T18:41:58.610+01:00
 * Generated source version: 3.2.1
 * 
 */
@WebServiceClient(name = "IzjasnjavanjeService", 
                  wsdlLocation = "classpath:wsdl/Izjasnjavanje.wsdl",
                  targetNamespace = "http://www.message") 
public class IzjasnjavanjeService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.message", "IzjasnjavanjeService");
    public final static QName IzjasnjavanjeServiceSoapBinding = new QName("http://www.message", "IzjasnjavanjeServiceSoapBinding");
    static {
        URL url = IzjasnjavanjeService.class.getClassLoader().getResource("wsdl/Izjasnjavanje.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(IzjasnjavanjeService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "classpath:wsdl/Izjasnjavanje.wsdl");
        }       
        WSDL_LOCATION = url;   
    }

    public IzjasnjavanjeService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public IzjasnjavanjeService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IzjasnjavanjeService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public IzjasnjavanjeService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public IzjasnjavanjeService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public IzjasnjavanjeService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns IzjasnjavanjeServicePortType
     */
    @WebEndpoint(name = "IzjasnjavanjeServiceSoapBinding")
    public IzjasnjavanjeServicePortType getIzjasnjavanjeServiceSoapBinding() {
        return super.getPort(IzjasnjavanjeServiceSoapBinding, IzjasnjavanjeServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IzjasnjavanjeServicePortType
     */
    @WebEndpoint(name = "IzjasnjavanjeServiceSoapBinding")
    public IzjasnjavanjeServicePortType getIzjasnjavanjeServiceSoapBinding(WebServiceFeature... features) {
        return super.getPort(IzjasnjavanjeServiceSoapBinding, IzjasnjavanjeServicePortType.class, features);
    }

}
