package com.project.poverenik.wsdl.resenje.ws;

import com.project.poverenik.wsdl.resenje.ObjectFactory;
import com.project.poverenik.wsdl.resenje.Tresenje;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2021-01-26T18:21:53.692+01:00
 * Generated source version: 3.2.1
 * 
 */
@WebService(targetNamespace = "http://resenje/ws", name = "ResenjePortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface ResenjePortType {

    @WebMethod
    @WebResult(name = "result", targetNamespace = "http://resenje/ws", partName = "result")
    public Tresenje getResenje(
        @WebParam(partName = "broj", name = "broj")
        String broj
    );
}
