
package com.project.poverenik.wsdl.resenje.ws;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import com.project.poverenik.wsdl.resenje.Tresenje;

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2021-01-26T19:01:30.370+01:00
 * Generated source version: 3.2.1
 * 
 */
public final class ResenjePortType_ResenjePort_Client {

    private static final QName SERVICE_NAME = new QName("http://resenje/ws", "ResenjeService");

    private ResenjePortType_ResenjePort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = ResenjeService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ResenjeService ss = new ResenjeService(wsdlURL, SERVICE_NAME);
        ResenjePortType port = ss.getResenjePort();  
        
        {
        System.out.println("Invoking getResenje...");
        String _getResenje_broj = "";
        Tresenje _getResenje__return = port.getResenje(_getResenje_broj);
        System.out.println("getResenje.result=" + _getResenje__return);


        }

        System.exit(0);
    }

}
