package com.project.poverenik.wsdl.resenje.ws;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2021-01-26T18:21:53.697+01:00
 * Generated source version: 3.2.1
 * 
 */
@WebServiceClient(name = "ResenjeService", 
                  wsdlLocation = "classpath:wsdl/Resenje.wsdl",
                  targetNamespace = "http://resenje/ws") 
public class ResenjeService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://resenje/ws", "ResenjeService");
    public final static QName ResenjePort = new QName("http://resenje/ws", "ResenjePort");
    static {
        URL url = ResenjeService.class.getClassLoader().getResource("wsdl/Resenje.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(ResenjeService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "classpath:wsdl/Resenje.wsdl");
        }       
        WSDL_LOCATION = url;   
    }

    public ResenjeService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ResenjeService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ResenjeService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public ResenjeService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ResenjeService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ResenjeService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns ResenjePortType
     */
    @WebEndpoint(name = "ResenjePort")
    public ResenjePortType getResenjePort() {
        return super.getPort(ResenjePort, ResenjePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ResenjePortType
     */
    @WebEndpoint(name = "ResenjePort")
    public ResenjePortType getResenjePort(WebServiceFeature... features) {
        return super.getPort(ResenjePort, ResenjePortType.class, features);
    }

}
